<a href="https://colab.research.google.com/github/Debo12/debo12.numpy.basic/blob/feature%2Flearning/numpy_array_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.arange(6).reshape(2, 3)
print(x)

[[0 1 2]
 [3 4 5]]


In [3]:
print(x+10, end='\n\n')
print(x*3, end='\n\n')
print(x%2)

[[10 11 12]
 [13 14 15]]

[[ 0  3  6]
 [ 9 12 15]]

[[0 1 0]
 [1 0 1]]


# Addition between two arrays

In [4]:
x = np.array([[1, 2], [-3, -4]])
y = np.array([[1, 2], [-3, -4]])

In [5]:
print(x+y, end='\n\n')

[[ 2  4]
 [-6 -8]]



In [6]:
print(x*y)

[[ 1  4]
 [ 9 16]]


In [10]:
x = np.array([[1, 2, 3], [-3, -4, -5]])
y = np.array([[10, 10, 10]])
print(x*y)

[[ 10  20  30]
 [-30 -40 -50]]


# Numpy Universal Functions

In [11]:
x = np.array([[1, 2], [3, 4]])
print(np.square(x), end='\n\n')
print(np.sin(x))

[[ 1  4]
 [ 9 16]]

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


In [14]:
x = np.array([[1, 2], [3, 4]])
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=1), end='\n\n')

10

[4 6]

[3 7]



In [15]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(x.tolist())

[[0, 1], [2, 3]]
