<a href="https://colab.research.google.com/github/Debo12/debo12.numpy.basic/blob/feature%2Flearning/numpy_array_indexing_slicing_iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1-D Array

In [2]:
import numpy as np

In [3]:
x = np.arange(5, 40, step=5)

In [4]:
print(x)

[ 5 10 15 20 25 30 35]


In [5]:
print(x[1])

10


In [6]:
print(x[1:5])

[10 15 20 25]


In [7]:
print(x[0:6:2])

[ 5 15 25]


# 2-D Array

In [9]:
x = np.arange(90).reshape(9, 10)

In [10]:
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]


In [11]:
print(x[1, 3])

13


In [14]:
print(x[0:5, 0:4])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [15]:
print(x[:, 1])

[ 1 11 21 31 41 51 61 71 81]
