<a href="https://colab.research.google.com/github/Debo12/Google_Colab_Project/blob/master/PythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**List**

In [70]:
name = 'iPhone 5s'
is_android = False
screen_size = 4.5

In [71]:
my_phone = [name, is_android, screen_size]

In [72]:
type(my_phone)

list

In [73]:
print(my_phone)

['iPhone 5s', False, 4.5]


In [74]:
my_phone[1:2]

[False]

In [75]:
my_dads_phone = my_phone

In [76]:
print(my_dads_phone)

['iPhone 5s', False, 4.5]


In [77]:
my_phone[2] = 4

In [78]:
print(my_phone)
print(my_dads_phone) # Not deep copying, reference adding

['iPhone 5s', False, 4]
['iPhone 5s', False, 4]


In [79]:
# To stop referencing and only copy
my_other_phone = list(my_phone)
# my_other_phone = my_phone[:]

In [80]:
my_phone[2] = 4.5

In [81]:
print(my_phone)
print(my_other_phone)

['iPhone 5s', False, 4.5]
['iPhone 5s', False, 4]


In [82]:
len(my_phone)

3

In [83]:
len?

In [84]:
my_phone.append('3G')

In [85]:
len(my_phone)

4

In [86]:
print(my_phone)

['iPhone 5s', False, 4.5, '3G']


In [87]:
iphone5s_some_pref = ['single sim', 35000]

In [88]:
my_phone = my_phone + iphone5s_some_pref # addition of two lists

In [89]:
print(my_phone)

['iPhone 5s', False, 4.5, '3G', 'single sim', 35000]


In [90]:
for data in my_phone:
  print(data)

iPhone 5s
False
4.5
3G
single sim
35000


In [91]:
range(5)

range(0, 5)

In [92]:
print(list(range(5))) #Convert range into list

[0, 1, 2, 3, 4]


In [93]:
a = list(range(5))

In [94]:
print(a)

[0, 1, 2, 3, 4]


In [95]:
b = list(map(lambda x: x**2, a)) # Map operator on list
print(b)

[0, 1, 4, 9, 16]


In [96]:
c = list(filter(lambda x: x%2==0, b))
print(c)

[0, 4, 16]


#**Tuple, Set and Dictionary**

In [97]:
print(my_phone)
type(my_phone)

['iPhone 5s', False, 4.5, '3G', 'single sim', 35000]


list

In [98]:
my_phone_tuple = ('iPhone 5s', False, 4.5)
print(my_phone_tuple)
type(my_phone_tuple)

('iPhone 5s', False, 4.5)


tuple

In [99]:
my_phone_tuple[0:2]

('iPhone 5s', False)

In [100]:
for data in my_phone_tuple:
  print(data)

iPhone 5s
False
4.5


In [101]:
my_phone_tuple[2] = 4 #Tuple is an imuutable dataset i.e once it is assigned, the value can't be altered

TypeError: ignored

In [ ]:
import time

In [ ]:
tic = time.time()
print(tic)

In [ ]:
tic = time.time()
# Do something to elapse time
toc = time.time()
print('Elapsed time', toc-tic)

In [ ]:
time.time?

In [ ]:
my_list = list(range(1000000))
tic = time.time()
my_squared_list = list(map(lambda x: x**2, my_list))
toc = time.time()
print('Elapsed time', toc-tic)

In [ ]:
my_tuple = list(range(1000000))
tic = time.time()
my_squared_tuple = list(map(lambda x: x**2, my_tuple))
toc = time.time()
print('Elapsed time', toc-tic)


**Important**
*   Tuple operation takes less time than list operation
*   Tuple is immutable object and list is a mutable object



**Sets**

In [ ]:
my_phone_set = set(my_phone)

In [ ]:
print(my_phone_set)

In [ ]:
my_phone.append(4.5)

In [ ]:
print(my_phone)

In [ ]:
my_phone_set = set(my_phone)

In [ ]:
my_phone_set.append('hi') #can not append set data

In [ ]:
print(my_phone_set)

In [ ]:
my_list = list(range(1000000))
tic = time.time()
print(98731 in my_list)
print(131591 in my_list)
print(1111111 in my_list)
toc = time.time()
print('Elapsed time', toc-tic)

In [ ]:
my_set = list(range(1000000))
tic = time.time()
print(98731 in my_set)
print(131591 in my_set)
print(1111111 in my_set)
toc = time.time()
print('Elapsed time', toc-tic)

In [ ]:
my_set = {5, 'iPhone', 4.5}
type(my_set)

**Dictionary**

In [ ]:
my_dict = {}
type(my_dict)

In [ ]:
my_dict['name'] = 'iPhone5s'
my_dict['is_android'] = False
my_dict['screen_size'] = 4.5

In [ ]:
print(my_dict)

In [ ]:
print(my_dict.keys())

In [ ]:
print(my_dict.values())

In [ ]:
print(my_dict.items())

In [ ]:
for key in my_dict.keys():
  print(key,' : ' ,my_dict[key])

#**Python Packages**

In [ ]:
import math

In [ ]:
a = math.sqrt(100)
print(a)

In [ ]:
b = math.pow(100, 0.5)
print(b)

In [ ]:
x = 100
y = 1

for i in range(1, x):
  y *= i

print('Factorial of', x, 'is: ',y)

In [ ]:
y = math.factorial(x)
print(y)

In [ ]:
import math as m

In [ ]:
y = m.factorial(100)
print(y)

In [ ]:
#when want to use factorial very often
from math import factorial
y = factorial(x)
print(y)

In [ ]:
import math, time

vals = list(range(1, 100))
result = 1
tic = time.time()
y = 1
for i in vals:
  y *= i
  result = y
toc = time.time()
print('Result: ', result, 'and elapse time: ', toc-tic)

tic = time.time()
y = math.factorial(x)
result = y
toc = time.time()
print('Result: ', result, 'and elapse time: ', toc-tic)

In [ ]:
!echo 'def hello():' > my_first_module.py
!echo '    print("hello, from another file!!!")' >> my_first_module.py

In [ ]:
!cat my_first_module.py 

In [ ]:
import my_first_module as m
m.hello()

In [ ]:
from my_first_module import hello
hello()

#**File Handling**

In [ ]:
!wget https://s3.amazonaws.com/thinkific-import/153034/mobile_cleaned-1549119762886.csv

In [ ]:
!ls

In [ ]:
file = open('mobile_cleaned-1549119762886.csv', mode='r')

In [ ]:
s = file.readline()
print(s)
type(s)

In [ ]:
print(s.split(',')) #SPlit string and get list

In [ ]:
file.close()

In [ ]:
file.readline()

In [ ]:
with open('mobile_cleaned-1549119762886.csv', 'r') as file:
  print(file.readline())

In [ ]:
with open('mobile_cleaned-1549119762886.csv', mode='r') as file:
  for line in file:
    for word in line.split(','):
      print(word)
    print('----')

In [ ]:
with open('my_first_file_handling', mode='w') as file:
  file.write('Hello from python code!!!')

In [ ]:
!cat my_first_file_handling

#**Classes**

In [102]:
class MobilePhone:
  '''This class is python class'''
  def __init__(self, name, is_android=False, screen_size=4.5):
    self.name = name
    self.is_android = is_android
    self.screen_size = screen_size
    self.rating = -1

  def hasRating(self):
    return self.rating>-1

In [103]:
new_phone = MobilePhone('iPhone5s')

In [105]:
type(new_phone)

__main__.MobilePhone

In [106]:
class iPhone(MobilePhone): #inheritance
  def __init__(self, name):
    MobilePhone.__init__(self, name, True, 4)

  def __str__(self): # prints the data of object as default string
    return self.name+' '+str(self.is_android)+' '+str(self.screen_size)+' '+str(self.rating)

In [107]:
new_iphone = iPhone('iPhone x')

In [108]:
print(new_iphone.screen_size)

4


In [109]:
MobilePhone.__doc__ #gets the documentation

'This class is python class'

In [110]:
print(new_iphone)

iPhone x True 4 -1


#**NumPy**
Numerical package

In [111]:
import numpy as np

In [112]:
X = np.array([1,2,3])

In [113]:
type(X)

numpy.ndarray

In [116]:
l = [4, 5, 10]
X = np.array(l)
print(type(l)) # list
print(type(X)) # numpy.ndarray

<class 'list'>
<class 'numpy.ndarray'>


In [117]:
print(X)

[ 4  5 10]


In [118]:
X = np.array(l, dtype='float') # convert into float

In [119]:
print(X)

[ 4.  5. 10.]


In [120]:
X.shape

(3,)

In [121]:
print(X.shape)

(3,)


In [122]:
np.array?

In [124]:
X = np.array([[1, 2, 3], [4, 5, 6]]) # two dimensional array

In [125]:
print(X)

[[1 2 3]
 [4 5 6]]


In [126]:
X.shape

(2, 3)

In [127]:
X[1, 1] # access individual element

5

In [129]:
print(X[1, 0:2]) # access range of element

[4 5]


In [130]:
print(X[0, :]) # access a row

[1 2 3]


In [133]:
X = np.zeros((4, 6), dtype=float) # inbuilt function (zeros)

In [134]:
print(X)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [135]:
X = np.eye(4, 4)
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [137]:
X = np.random.random((4, 5)) # random number matrix
print(X)

[[0.49154701 0.8156794  0.06270972 0.59939061 0.1868614 ]
 [0.57064599 0.63786722 0.80063637 0.833863   0.80420996]
 [0.85333294 0.03848185 0.41577322 0.47202166 0.52773222]
 [0.19545353 0.77785983 0.22754463 0.56147866 0.07618432]]


In [138]:
Z = X.T # transpose a matrix
print(Z)

[[0.49154701 0.57064599 0.85333294 0.19545353]
 [0.8156794  0.63786722 0.03848185 0.77785983]
 [0.06270972 0.80063637 0.41577322 0.22754463]
 [0.59939061 0.833863   0.47202166 0.56147866]
 [0.1868614  0.80420996 0.52773222 0.07618432]]


In [139]:
Y = X.reshape((10, 2)) # reshape the matrix into 10 rows and 2 columns
print(Y)

[[0.49154701 0.8156794 ]
 [0.06270972 0.59939061]
 [0.1868614  0.57064599]
 [0.63786722 0.80063637]
 [0.833863   0.80420996]
 [0.85333294 0.03848185]
 [0.41577322 0.47202166]
 [0.52773222 0.19545353]
 [0.77785983 0.22754463]
 [0.56147866 0.07618432]]


In [140]:
A = np.arange(5) # function like range
B = np.arange(5)

In [141]:
print(A)
print(B)

[0 1 2 3 4]
[0 1 2 3 4]


In [142]:
print(A+B)
print(A-B)
print(A*B)

[0 2 4 6 8]
[0 0 0 0 0]
[ 0  1  4  9 16]


In [143]:
print(A, A+1) # broadcasting - scalar value will be added to individual vector element

[0 1 2 3 4] [1 2 3 4 5]


In [145]:
A = np.random.random((2, 3))
print(A)
print('--------------------')
print(A+1)

[[0.90871465 0.25966024 0.72855389]
 [0.81210197 0.58344822 0.23549782]]
--------------------
[[1.90871465 1.25966024 1.72855389]
 [1.81210197 1.58344822 1.23549782]]


In [148]:
A = np.random.random((2, 3))*10
print(A)
print('--------------------')
print(np.floor(A))

[[2.22390407 6.05324597 3.47703097]
 [4.37184578 9.80840835 4.23319403]]
--------------------
[[2. 6. 3.]
 [4. 9. 4.]]


In [150]:
u = [1, 2, 3]
v = [-1, 0, 1]

p1 = np.inner(u, v) # inner product
print(p1)

2


In [151]:
p2 = np.outer(u, v) # outer product
print(p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [154]:
A = np.ones((2, 3))
print(A)
B = np.ones((3, 2))

print(np.dot(A, B))

[[1. 1. 1.]
 [1. 1. 1.]]
[[3. 3.]
 [3. 3.]]


In [157]:
print(np.dot(B.T, A.T))

[[3. 3.]
 [3. 3.]]


In [159]:
A = np.ones((2, 3))
print(A.sum())

6.0


In [160]:
print(A.sum(axis=0))

[2. 2. 2.]


In [161]:
print(A.sum(axis=1))

[3. 3.]


In [162]:
A.max()

1.0